import Head from 'next/head'
import Banner from '../components/common/banner'
import ListProduct from '../components/common/listProduct'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NZ Bakery | The best bakery store in Cilacap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner />

        <ListProduct />
      </main>

    </div>
  )
}
