import Head from 'next/head'
import Banner from '../components/common/banner'
import Benefit from '../components/common/benefit'
import ListProduct from '../components/common/listProduct'
import Testimony from '../components/common/testimony'

export default function Home() {
  return (
    <>
      <Head>
        <title>NZ Bakery | The best bakery store in Cilacap</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />

      <ListProduct />

      <Benefit />

      <Testimony />

    </>
  )
}
